version: "3.7"

services:
  main:
    build: .
    networks:
      - flasknet
    ports:
      - 8080:8080
    working_dir: /app
  nginx:
    build: ./nginx
    networks:
      - flasknet
    expose:
      - 8100
    ports:
      - 8100:8100

networks:
  flasknet: